import Head from 'next/head'

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from "@/components/hero"
import Link from 'next/link'
import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <Hero/>
       <section className={styles.aboutus}>
        <div className={styles.content}>
          <p>
          Are you a Kenyan national or an expat living in Kenya? We&#39;ll help you explore Kenya, the wider eastern Africa, and the rest of the world.
          </p>
          <p>
          Are you a Kenyan national or an expat living in Kenya? We&#39;ll help you explore Kenya, the wider eastern Africa, and the rest of the world.
          </p>
          <p>
          We&#39;re always ready to serve you. We&#39;ll help you book your hotels, book your flight, organize airport transfers, choose the best and most unique destinations for your tours. Anything to make your travel convenient & affordable. This way, you can explore, meet new people & create lasting memories.
          </p>
          <p>
            Reach out to us on <span><Link href="/contacts">our contacts</Link></span> or view our <span><Link href="/tours">packages</Link></span>
          </p>

        </div>
        <p style={{fontWeight:"300", fontSize:"1.3rem", textAlign:"center", marginBlock:"2rem", color:"teal"}}>Popular Holidays</p>
        <div className={styles.cards}>
         
          <div className={styles.card}>
            <div className={styles.cardImgwrapper}>
              <Image src="/hero.jpg" alt="" fill className={styles.cardImg}/>
            </div>
            <div className={styles.cardContent}>
            <h3>
              3 Days Maasai Mara Group Joining Safari (2023 wildebeest migration)
            </h3>
            <p>
            3 Days Amboseli Christmas Safari Packages: Tour Overview This is a 3 Days Amboseli Christmas safari that starts and ends in Nairobi or Mombasa. The 2022 prices …
            </p>
            </div>
          </div>
          <div className={styles.card}>
            <div className={styles.cardImgwrapper}>
              <Image src="/hero.jpg" alt="" fill className={styles.cardImg}/>
            </div>
            <div className={styles.cardContent}>
            <h3>
              3 Days Maasai Mara Group Joining Safari (2023 wildebeest migration)
            </h3>
            <p>
            3 Days Amboseli Christmas Safari Packages: Tour Overview This is a 3 Days Amboseli Christmas safari that starts and ends in Nairobi or Mombasa. The 2022 prices …
            </p>
            </div>
          </div>
          <div className={styles.card}>
            <div className={styles.cardImgwrapper}>
              <Image src="/hero.jpg" alt="" fill className={styles.cardImg}/>
            </div>
            <div className={styles.cardContent}>
            <h3>
              3 Days Maasai Mara Group Joining Safari (2023 wildebeest migration)
            </h3>
            <p>
            3 Days Amboseli Christmas Safari Packages: Tour Overview This is a 3 Days Amboseli Christmas safari that starts and ends in Nairobi or Mombasa. The 2022 prices …
            </p>
            </div>
          </div>
        </div>
       </section>
      </main>
    </>
  )
}
